server:
  port: 8085
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/userServiceFallback

        - id: STOCK-SERVICE
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stocks/**
          filters:
            - name: CircuitBreaker
              args:
                name: stockCircuitBreaker
                fallbackUri: forward:/stockServiceFallback

        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
                fallbackUri: forward:/orderServiceFallback

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentCircuitBreaker
                fallbackUri: forward:/paymentServiceFallback

        - id: FRONTEND-SERVICE
          uri: lb://FRONTEND-SERVICE
          predicates:
            - Path=/**
          filters:
            - name: CircuitBreaker
              args:
                name: frontendCircuitBreaker
                fallbackUri: forward:/frontendServiceFallback


okta:
  oauth2:
    issuer: https://dev-13111923.okta.com/oauth2/default
    audience: api://default
    client-id: 0oab0jwce6zd4y2rI5d7
    client-secret: i8meEZg5eSQPmDh6MmKBM6lQvHegKZO0b-JVWpA5B3ySZHcydgNU39YrY5SM4S0U
    scopes: openid, email, profile, offline_access
