server:
  port: 8086

spring:
  application:
    name: FRONTEND-SERVICE
  config:
    import: configserver:http://localhost:9296
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
